export const allCards = [
  { id: 1, value: "France", pairId: 1, type: "text" },
  { id: 9, value: "England", pairId: 5, type: "text" },
  { id: 15, value: "Spain", pairId: 8, type: "text" },
  { id: 2, value: "(nước) Pháp", pairId: 1, type: "text" },
  { id: 3, value: "Japan", pairId: 2, type: "text" },
  { id: 5, value: "Korea", pairId: 3, type: "text" },
  { id: 14, value: "(nước) Ý", pairId: 7, type: "text" },
  { id: 6, value: "(nước) Hàn Quốc", pairId: 3, type: "text" },
  { id: 7, value: "China", pairId: 4, type: "text" },
  { id: 8, value: "(nước) Trung Quốc", pairId: 4, type: "text" },
  { id: 4, value: "(nước) Nhật", pairId: 2, type: "text" },
  { id: 11, value: "Germany", pairId: 6, type: "text" },
  { id: 12, value: "(nước) Đức", pairId: 6, type: "text" },
  { id: 13, value: "Italy", pairId: 7, type: "text" },
  { id: 10, value: "(nước) Anh", pairId: 5, type: "text" },
  { id: 16, value: "tây ban nha", pairId: 8, type: "text" },
  { id: 17, value: "Japan", pairId: 2, type: "text" },
];
