import { icons, images } from "@/assets";

export const exercise = {
  id: 23,
  title: "Thực hành nghe",
  progress: 60,
  total: 10,
  done: 6,
  type: "listening",
  exerciseList: [
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: ["is", "from", "Elisa", "MariaDb"],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next class is on the ____________.",
      answer: "Elisa2",

      answerOptions: ["is2", "from2", "Elisa2", "MariaDb2"],
      sound: icons.audio,
      status: "progress",
    },
  ],
};
export const exerciseReading = {
  id: 23,
  title: "Thực hành nghe",
  progress: 60,
  total: 10,
  done: 6,
  type: "listening",
  exerciseList: [
    {
      id: 1,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: [
        { value: 1, label: "A. Option" },
        { value: 2, label: "B. Option" },
        { value: 3, label: "C. Option" },
      ],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 2,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: [
        { value: 1, label: "A. Option" },
        { value: 2, label: "B. Option" },
        { value: 3, label: "C. Option" },
      ],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 3,
      question: "My next ____________ class is on the.",
      answer: "is",
      answerOptions: [
        { value: 1, label: "A. Option" },
        { value: 2, label: "B. Option" },
        { value: 3, label: "C. Option" },
      ],
      sound: icons.audio,
      status: "completed",
    },
    {
      id: 4,
      question: "My next  class is on the____________.",
      answer: "is",
      answerOptions: [
        { value: 1, label: "A. Option" },
        { value: 2, label: "B. Option" },
        { value: 3, label: "C. Option" },
      ],
      sound: icons.audio,
      status: "completed",
    },
  ],
};
export const exerciseLearnVocab = {
  id: 23,
  title: "Thực hành nghe",
  progress: 60,
  total: 10,
  done: 6,
  type: "listening",
  exerciseList: [
    {
      id: 1,
      icons: images.userSit,
      answer: "sit",
      meaning: "Ngồi",
      transcription: "/sit/",
      sound: icons.audio,
      status: "completed",
      wordType: "v",
    },
    {
      id: 2,
      icons: images.userSit,
      answer: "sit",
      meaning: "Ngồi",
      transcription: "/sit/",
      sound: icons.audio,
      status: "completed",
      wordType: "v",
    },
    {
      id: 3,
      icons: images.userSit,
      answer: "sit",
      meaning: "Ngồi",
      transcription: "/sit/",
      sound: icons.audio,
      status: "completed",
      wordType: "v",
    },
  ],
};
